### ISSUE TITLE
Support for bytes

### ISSUE THREAD

**Issue by marcglobality** [ynqa/pandavro#27]
Hi! first of all, thanks for this very useful package. We use it in our ETL and it's really convenient.

I wonder whether there is support for bytes and I missed it. When I add a column to the dataframe being bytes, I get the error 

```
TypeError: argument of type 'NoneType' is not iterable
```

which I'm getting with other complex types. This doesn't seem a very complex type, so I wonder if it'd be very difficult to add. 

At the moment what I'm doing is this:

```
schema = pdx.schema_infer(df)
bytes_field_idx = next(idx for idx, field in enumerate(schema["fields"]) if field["name"] == "bytes_field")
schema["fields"][bytes_field_idx]["type"] = ["null", "bytes"]

pdx.to_avro(
        str(path),
        df,
        schema=schema,
)
```

but ofc would be great if I could delegate everything to `schema_infer`. Am I missing something? It'd be great to support Pathlib.Path as well, but that's not such a big deal :)

**Comment by marctorsoc** [comment]
Now that tests are fixed in master, I can contribute to this. What are your thoughts about the above? @ynqa

**Comment by Defman** [comment]
The same error occurs when a column contains None and np.array([float])

**Comment by marcglobality** [comment]
@Defman my PR showed how to support bytes. Feel free to add a PR for other types. But keep in mind they need to he supported by the avro format.

For those other not supported types, I have a datareader, that serializes and deserializes the data. Essentially i mean convert to string and then back to whatever
