### ISSUE TITLE
Tests failing in master

### ISSUE THREAD

**Issue by marctorsoc** [ynqa/pandavro#28]
Hi, I was thinking about contributing to https://github.com/ynqa/pandavro/issues/27, but just ran tests in master and they fail for me

```
FAILED tests/pandavro_test.py::test_buffer_e2e - AssertionError: numpy array are different
FAILED tests/pandavro_test.py::test_file_path_e2e - AssertionError: numpy array are different
FAILED tests/pandavro_test.py::test_delegation - AssertionError: numpy array are different
FAILED tests/pandavro_test.py::test_append - AssertionError: numpy array are different
FAILED tests/pandavro_test.py::test_dataframe_kwargs - AssertionError: numpy array are different
========================= 5 failed, 4 passed, 5 warnings in 0.60s ===========================
```

I can see 
```
(Pdb) expect
   Boolean          DateTime64   Float64  Int64 String
0     True 2018-12-31 23:00:00 -0.579613      8    foo
1    False 2019-01-01 23:00:00 -0.922827      3    bar
2     True 2019-01-02 23:00:00 -1.070658      8    foo
3    False 2019-01-03 23:00:00 -0.072218      2    bar
4     True 2019-01-04 23:00:00 -1.604049      3    foo
5    False 2019-01-05 23:00:00 -0.822774      0    bar
6     True 2019-01-06 23:00:00 -0.504930      4    foo
7    False 2019-01-07 23:00:00  1.357435      0    bar
(Pdb) dataframe
   Boolean DateTime64   Float64  Int64 String
0     True 2019-01-01 -0.579613      8    foo
1    False 2019-01-02 -0.922827      3    bar
2     True 2019-01-03 -1.070658      8    foo
3    False 2019-01-04 -0.072218      2    bar
4     True 2019-01-05 -1.604049      3    foo
5    False 2019-01-06 -0.822774      0    bar
6     True 2019-01-07 -0.504930      4    foo
7    False 2019-01-08  1.357435      0    bar
```

in `test_append`. Any ideas? There's like a mismatch of 1h, maybe some rounding issue? @ynqa

**Comment by marctorsoc** [comment]
@ynqa ?

**Comment by ynqa** [comment]
@marctorsoc Sorry for the responses late. Please check #29. I changed the versions of python and our dependencies (e.g. pandas) for testing successful.

**Comment by marctorsoc** [comment]
that's great!

**Comment by marctorsoc** [comment]
actually, I just ran this on mac and it failed for me... not sure if Travis allows you to add mac for free as well to the CI? it seems to be taking 1 day less or more for dates, which makes the tests to fail

**Comment by ynqa** [comment]
Mac env is not free, and I do not any plans to build other platforms now.
- https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

Please put here for more details about the error and your laptop environment (in particular, you will encounter various kinds of errors if M1 Mac). Otherwise, is it better to prepare dockerfile (or something) for the developers' envs?

**Comment by marctorsoc** [comment]
The problem (I think) is related to https://stackoverflow.com/questions/8558919/mktime-and-tm-isdst). `mktime` is deep inside the calls in this library. So it's fine, I just ignore timestamps while in local and then run all tests in travis crossing fingers later :D
