### ISSUE TITLE
pypi homepage points to the wrong link

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [ynqa/pandavro#3]
The "Home Page" link in https://pypi.python.org/pypi/pandavro/1.0.0 points to https://github.com/ynqa/pandabro instead of https://github.com/ynqa/pandavro (notice the typo pandabro vs. pandavro) . I am wondering if this can be corrected?

PS: Not sure if this is the correct place to report this issue as the typo is in the pypi listing page. I am reporting here since I do not have an account in pypi,

**Comment by ynqa** [comment]
Oh! Probably it's occurred owing to my typo in `setup.py`:
https://github.com/ynqa/pandavro/blob/master/setup.py#L8 
Thank you for reporting! I'll fix it soon.
