### ISSUE TITLE
Add compatibility with Python 3.11

### ISSUE THREAD

**Issue by jbvaningen** [ynqa/pandavro#44]
The current version `pandavro==1.7.1` is not compatible with Python 3.11 because of the pinned dependency `fastavro==1.5.1`. I would like to request to fix this, so any app using `pandavro` can be upgraded to the latest version of Python.

I understand that this issue is closely related to https://github.com/ynqa/pandavro/issues/39, but I still decided to open it for raising awareness.

**Comment by FloChehab** [comment]
Hello @ynqa,

I hope this comments finds you well!
Do you have update strategy for the issue at stake? I would be very happy to have access to a python3.11 wheel.
If you need any help, let me know.
