### ISSUE TITLE
Problem with datatype datetime64[ns]

### ISSUE THREAD

**Issue by jpardobl** [ynqa/pandavro#6]
I'm having an issue trying to convert a Apache Parquet file into an Apache Avro file.

This is the code:

`import pyarrow.parquet as pq
import pandavro as pdx

table = pq.read_table('/media/sf_AWS/kafka/acciones_postcorte.parq')
pdx.to_avro('opers.avro', table.to_pandas())`

This is the schema of the file:

> divpol: string
division: string
poliza: string
asignacion: string
num_asignacion: string
f_asignacion: timestamp[ms]
campana: string
campanacontable: string
despacho_empresa: string
municipio: string
deudagestionar: double
deudavencida: double
d_oap: double
fresultado: timestamp[ms]
resultado: string
gestor: string
captura: timestamp[ms]
gpo1: string
toap: string
visitado: int64
visitado_aus: int64
ps_ano: timestamp[ms]
dg_filepath: string
dg_date: timestamp[ms]
dg_schema_version: int64
__index_level_0__: int64
metadata
--------
{b'pandas': b'{"index_columns": ["__index_level_0__"], "column_indexes": [{"na'
            b'me": null, "field_name": null, "pandas_type": "unicode", "numpy_'
            b'type": "object", "metadata": {"encoding": "UTF-8"}}], "columns":'
            b' [{"name": "divpol", "field_name": "divpol", "pandas_type": "uni'
            b'code", "numpy_type": "object", "metadata": null}, {"name": "divi'
            b'sion", "field_name": "division", "pandas_type": "unicode", "nump'
            b'y_type": "object", "metadata": null}, {"name": "poliza", "field_'
            b'name": "poliza", "pandas_type": "unicode", "numpy_type": "object'
            b'", "metadata": null}, {"name": "asignacion", "field_name": "asig'
            b'nacion", "pandas_type": "unicode", "numpy_type": "object", "meta'
            b'data": null}, {"name": "num_asignacion", "field_name": "num_asig'
            b'nacion", "pandas_type": "unicode", "numpy_type": "object", "meta'
            b'data": null}, {"name": "f_asignacion", "field_name": "f_asignaci'
            b'on", "pandas_type": "datetime", "numpy_type": "datetime64[ns]", '
            b'"metadata": null}, {"name": "campana", "field_name": "campana", '
            b'"pandas_type": "unicode", "numpy_type": "object", "metadata": nu'
            b'll}, {"name": "campanacontable", "field_name": "campanacontable"'
            b', "pandas_type": "unicode", "numpy_type": "object", "metadata": '
            b'null}, {"name": "despacho_empresa", "field_name": "despacho_empr'
            b'esa", "pandas_type": "unicode", "numpy_type": "object", "metadat'
            b'a": null}, {"name": "municipio", "field_name": "municipio", "pan'
            b'das_type": "unicode", "numpy_type": "object", "metadata": null},'
            b' {"name": "deudagestionar", "field_name": "deudagestionar", "pan'
            b'das_type": "float64", "numpy_type": "float64", "metadata": null}'
            b', {"name": "deudavencida", "field_name": "deudavencida", "pandas'
            b'_type": "float64", "numpy_type": "float64", "metadata": null}, {'
            b'"name": "d_oap", "field_name": "d_oap", "pandas_type": "float64"'
            b', "numpy_type": "float64", "metadata": null}, {"name": "fresulta'
            b'do", "field_name": "fresultado", "pandas_type": "datetime", "num'
            b'py_type": "datetime64[ns]", "metadata": null}, {"name": "resulta'
            b'do", "field_name": "resultado", "pandas_type": "unicode", "numpy'
            b'_type": "object", "metadata": null}, {"name": "gestor", "field_n'
            b'ame": "gestor", "pandas_type": "unicode", "numpy_type": "object"'
            b', "metadata": null}, {"name": "captura", "field_name": "captura"'
            b', "pandas_type": "datetime", "numpy_type": "datetime64[ns]", "me'
            b'tadata": null}, {"name": "gpo1", "field_name": "gpo1", "pandas_t'
            b'ype": "unicode", "numpy_type": "object", "metadata": null}, {"na'
            b'me": "toap", "field_name": "toap", "pandas_type": "unicode", "nu'
            b'mpy_type": "object", "metadata": null}, {"name": "visitado", "fi'
            b'eld_name": "visitado", "pandas_type": "int64", "numpy_type": "in'
            b't64", "metadata": null}, {"name": "visitado_aus", "field_name": '
            b'"visitado_aus", "pandas_type": "int64", "numpy_type": "int64", "'
            b'metadata": null}, {"name": "ps_ano", "field_name": "ps_ano", "pa'
            b'ndas_type": "datetime", "numpy_type": "datetime64[ns]", "metadat'
            b'a": null}, {"name": "dg_filepath", "field_name": "dg_filepath", '
            b'"pandas_type": "unicode", "numpy_type": "object", "metadata": nu'
            b'll}, {"name": "dg_date", "field_name": "dg_date", "pandas_type":'
            b' "datetime", "numpy_type": "datetime64[ns]", "metadata": null}, '
            b'{"name": "dg_schema_version", "field_name": "dg_schema_version",'
            b' "pandas_type": "int64", "numpy_type": "int64", "metadata": null'
            b'}, {"name": null, "field_name": "__index_level_0__", "pandas_typ'
            b'e": "int64", "numpy_type": "int64", "metadata": null}], "pandas_'
            b'version": "0.22.0"}'}

This is the error:

`Traceback (most recent call last):
  File "p2a.py", line 10, in <module>
    pdx.to_avro('opers.avro', table.to_pandas())
  File "/home/jpardobl/python_envs/venv_kafka/lib/python3.6/site-packages/pandavro/__init__.py", line 77, in to_avro
    schema = __schema_infer(df)
  File "/home/jpardobl/python_envs/venv_kafka/lib/python3.6/site-packages/pandavro/__init__.py", line 33, in __schema_infer
    fields = __fields_infer(df)
  File "/home/jpardobl/python_envs/venv_kafka/lib/python3.6/site-packages/pandavro/__init__.py", line 27, in __fields_infer
    type_avro = __type_infer(type_np)
  File "/home/jpardobl/python_envs/venv_kafka/lib/python3.6/site-packages/pandavro/__init__.py", line 21, in __type_infer
    raise TypeError('Invalid type: {}'.format(t))
TypeError: Invalid type: datetime64[ns]
`

**Comment by ynqa** [comment]
@jpardobl Thanks for your issues. I've not yet converted `np.datetime64` into Avro [date](https://avro.apache.org/docs/1.8.0/spec.html#Date).

**Comment by ynqa** [comment]
@jpardobl tackled on #11.
